//! Golden test: compare candle-birefnet inference against PyTorch BiRefNet.
//!
//! Test data generated by `scripts/generate_golden_data.py` (Swin-L)
//! and `scripts/generate_golden_data_lite.py` (Swin-T).
//! Run the corresponding script to regenerate.

use candle_core::{DType, Device, Result, Tensor, Var};
use candle_nn::{VarBuilder, VarMap};
use std::collections::HashMap;

fn load_test_case(name: &str) -> HashMap<String, Tensor> {
    let path = format!("test-data/{name}.safetensors");
    let data = std::fs::read(&path).unwrap_or_else(|_| panic!("missing test data: {path}"));
    let tensors = safetensors::SafeTensors::deserialize(&data).unwrap();
    let device = &Device::Cpu;
    tensors
        .tensors()
        .into_iter()
        .map(|(name, view)| {
            let dtype = match view.dtype() {
                safetensors::Dtype::F32 => DType::F32,
                safetensors::Dtype::F64 => DType::F64,
                safetensors::Dtype::I64 => DType::I64,
                safetensors::Dtype::U32 => DType::U32,
                dt => panic!("unsupported dtype {dt:?} for tensor {name}"),
            };
            let tensor = Tensor::from_raw_buffer(view.data(), dtype, view.shape(), device).unwrap();
            (name.to_string(), tensor)
        })
        .collect()
}

fn vb_from_params(data: &HashMap<String, Tensor>) -> (VarMap, VarBuilder<'_>) {
    let varmap = VarMap::new();
    {
        let mut data_map = varmap.data().lock().unwrap();
        for (key, tensor) in data {
            if let Some(param_name) = key.strip_prefix("param.") {
                data_map.insert(param_name.to_string(), Var::from_tensor(tensor).unwrap());
            }
        }
    }
    let vb = VarBuilder::from_varmap(&varmap, DType::F32, &Device::Cpu);
    (varmap, vb)
}

fn assert_tensor_close(actual: &Tensor, expected: &Tensor, atol: f64) {
    let diff = actual
        .to_dtype(DType::F64)
        .unwrap()
        .sub(&expected.to_dtype(DType::F64).unwrap())
        .unwrap()
        .abs()
        .unwrap();

    let max_diff: f64 = diff
        .flatten_all()
        .unwrap()
        .max(0)
        .unwrap()
        .to_scalar::<f64>()
        .unwrap();
    let mean_diff: f64 = diff.mean_all().unwrap().to_scalar::<f64>().unwrap();

    println!("  max_diff={max_diff:.6e}  mean_diff={mean_diff:.6e}  tolerance={atol:.0e}");
    assert!(
        diff.flatten_all()
            .unwrap()
            .max(0)
            .unwrap()
            .to_scalar::<f64>()
            .unwrap()
            < atol,
        "max abs diff: {max_diff}, tolerance: {atol}"
    );
}

/// End-to-end BiRefNet inference test with pretrained weights.
///
/// Loads the official BiRefNet model weights, runs inference on a 384x384 input,
/// and compares the segmentation mask output against PyTorch reference.
#[test]
fn golden_birefnet_full_inference() -> Result<()> {
    let data = load_test_case("birefnet_full");
    let (_varmap, vb) = vb_from_params(&data);

    let model = candle_birefnet::BiRefNet::new(vb)?;
    let outputs = model.forward(&data["input"])?;

    assert_eq!(outputs.len(), 1);
    assert_eq!(outputs[0].dims(), &[1, 1, 384, 384]);
    assert_eq!(outputs[0].dims(), data["output"].dims());

    println!("\nBiRefNet 384x384 inference error:");
    // Actual max error: ~6.87e-5 across full end-to-end inference
    assert_tensor_close(&outputs[0], &data["output"], 1e-3);
    Ok(())
}

/// BiRefNet inference at 1024x1024 resolution.
#[test]
fn golden_birefnet_1024_inference() -> Result<()> {
    let data = load_test_case("birefnet_1024");
    let (_varmap, vb) = vb_from_params(&data);

    let model = candle_birefnet::BiRefNet::new(vb)?;
    let outputs = model.forward(&data["input"])?;

    assert_eq!(outputs.len(), 1);
    assert_eq!(outputs[0].dims(), &[1, 1, 1024, 1024]);

    println!("\nBiRefNet 1024x1024 inference error:");
    assert_tensor_close(&outputs[0], &data["output"], 1e-2);
    Ok(())
}

/// BiRefNet_lite (Swin-V1-Tiny backbone) inference test at 384x384.
///
/// Loads BiRefNet_lite pretrained weights, runs inference, and compares
/// segmentation mask output against PyTorch reference.
#[test]
fn golden_birefnet_lite_inference() -> Result<()> {
    let data = load_test_case("birefnet_lite");
    let (_varmap, vb) = vb_from_params(&data);

    let model = candle_birefnet::BiRefNet::new_lite(vb)?;
    let outputs = model.forward(&data["input"])?;

    assert_eq!(outputs.len(), 1);
    assert_eq!(outputs[0].dims(), &[1, 1, 384, 384]);
    assert_eq!(outputs[0].dims(), data["output"].dims());

    println!("\nBiRefNet_lite 384x384 inference error:");
    assert_tensor_close(&outputs[0], &data["output"], 1e-3);
    Ok(())
}

/// BiRefNet_lite INT8 dequantize → inference test.
///
/// Verifies that Rust-side INT8 dequantization produces the same output
/// as Python-side dequantization. This catches bugs in broadcast shape,
/// sign handling, or scale/zero_point application.
///
/// Test data: Python loads INT8 safetensors, dequantizes, runs inference,
/// saves dequantized weights + output. Rust loads the same dequantized
/// weights, runs inference, and compares.
#[test]
fn golden_birefnet_int8_dequantized_inference() -> Result<()> {
    let data = load_test_case("birefnet_int8_dequantized");
    let (_varmap, vb) = vb_from_params(&data);

    let model = candle_birefnet::BiRefNet::new_lite(vb)?;
    let outputs = model.forward(&data["input"])?;

    assert_eq!(outputs.len(), 1);
    assert_eq!(outputs[0].dims(), &[1, 1, 384, 384]);
    assert_eq!(outputs[0].dims(), data["output"].dims());

    println!("\nBiRefNet_lite INT8 dequantized 384x384 inference error:");
    // INT8 dequantized weights introduce quantization noise,
    // so tolerance is higher than FP32 (1e-3 vs 1e-3 for lite FP32)
    assert_tensor_close(&outputs[0], &data["output"], 1e-3);
    Ok(())
}

/// BiRefNet_lite INT8 raw file → Rust dequantize → inference test.
///
/// End-to-end: loads the actual INT8 safetensors file, runs Rust dequantize
/// logic, builds model, runs inference, and compares against Python output.
/// This validates the full Rust INT8 loading pipeline.
#[test]
fn golden_birefnet_int8_rust_dequantize() -> Result<()> {
    // Load Python reference (input + expected output from INT8 dequantized model)
    let ref_data = load_test_case("birefnet_int8_dequantized");

    // Load INT8 safetensors and dequantize in Rust
    let int8_path = "weights/birefnet_int8.safetensors";
    let int8_bytes = std::fs::read(int8_path)
        .unwrap_or_else(|_| panic!("missing INT8 weights: {int8_path}"));

    let device = &Device::Cpu;
    let int8_tensors = safetensors::SafeTensors::deserialize(&int8_bytes).unwrap();

    // Step 1: Load all tensors
    let mut raw: std::collections::HashMap<String, Tensor> = std::collections::HashMap::new();
    for (name, view) in int8_tensors.tensors() {
        if view.dtype() == safetensors::Dtype::I8 {
            let f32_data: Vec<f32> = view.data().iter().map(|&b| (b as i8) as f32).collect();
            let tensor = Tensor::from_vec(f32_data, view.shape(), device)?;
            raw.insert(name.to_string(), tensor);
        } else {
            let dtype = match view.dtype() {
                safetensors::Dtype::F32 => DType::F32,
                safetensors::Dtype::F16 => DType::F16,
                safetensors::Dtype::I64 => DType::I64,
                safetensors::Dtype::U32 => DType::U32,
                _ => continue,
            };
            let tensor = Tensor::from_raw_buffer(view.data(), dtype, view.shape(), device)?;
            raw.insert(name.to_string(), tensor);
        }
    }

    // Step 2: Dequantize INT8 weights
    let varmap = VarMap::new();
    {
        let mut data_map = varmap.data().lock().unwrap();
        let weight_keys: Vec<String> = raw
            .keys()
            .filter(|k| !k.ends_with(".__scale") && !k.ends_with(".__zero_point"))
            .cloned()
            .collect();

        for key in weight_keys {
            let tensor = &raw[&key];
            let scale_key = format!("{key}.__scale");
            let zp_key = format!("{key}.__zero_point");

            let final_tensor = if raw.contains_key(&scale_key) {
                let scale = raw[&scale_key].to_dtype(DType::F32)?;
                let zp = raw[&zp_key].to_dtype(DType::F32)?;
                let w = tensor.to_dtype(DType::F32)?;

                let w_dims = w.dims().len();
                if w_dims > 1 {
                    let mut shape = vec![scale.dims()[0]];
                    for _ in 1..w_dims {
                        shape.push(1);
                    }
                    let scale_b = scale.reshape(&shape[..])?;
                    let zp_b = zp.reshape(&shape[..])?;
                    w.broadcast_sub(&zp_b)?.broadcast_mul(&scale_b)?
                } else {
                    w.sub(&zp)?.mul(&scale)?
                }
            } else {
                tensor.to_dtype(DType::F32)?
            };

            data_map.insert(key, Var::from_tensor(&final_tensor)?);
        }
    }

    let vb = VarBuilder::from_varmap(&varmap, DType::F32, device);
    let model = candle_birefnet::BiRefNet::new_lite(vb)?;
    let outputs = model.forward(&ref_data["input"])?;

    assert_eq!(outputs.len(), 1);
    assert_eq!(outputs[0].dims(), &[1, 1, 384, 384]);

    println!("\nBiRefNet_lite INT8 Rust-dequantized 384x384 inference error:");
    // Compare Rust dequantize output against Python dequantize output
    // Should be very close (same dequantize formula, same weights)
    assert_tensor_close(&outputs[0], &ref_data["output"], 1e-3);
    Ok(())
}
